# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_arm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'robot_arm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frobot_arm.proto\x12\x08robotarm\"\x86\x01\n\x0bPlanRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\x12\x12\n\nimage_left\x18\x03 \x01(\x0c\x12\x13\n\x0bimage_right\x18\x04 \x01(\x0c\x12\x17\n\x0f\x64\x65tections_json\x18\x05 \x01(\t\x12\x18\n\x10robot_state_json\x18\x06 \x01(\t\"\x86\x01\n\x0cPlanResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\t\x12\x10\n\x08\x64sl_json\x18\x04 \x01(\t\x12\r\n\x05valid\x18\x05 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x06 \x01(\t\x12\x11\n\telapsed_s\x18\x07 \x01(\x02\"\x0f\n\rHealthRequest\"4\n\x0eHealthResponse\x12\x14\n\x0cmodels_ready\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t2\x80\x01\n\nRobotArmAI\x12\x35\n\x04Plan\x12\x15.robotarm.PlanRequest\x1a\x16.robotarm.PlanResponse\x12;\n\x06Health\x12\x17.robotarm.HealthRequest\x1a\x18.robotarm.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_arm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANREQUEST']._serialized_start=30
  _globals['_PLANREQUEST']._serialized_end=164
  _globals['_PLANRESPONSE']._serialized_start=167
  _globals['_PLANRESPONSE']._serialized_end=301
  _globals['_HEALTHREQUEST']._serialized_start=303
  _globals['_HEALTHREQUEST']._serialized_end=318
  _globals['_HEALTHRESPONSE']._serialized_start=320
  _globals['_HEALTHRESPONSE']._serialized_end=372
  _globals['_ROBOTARMAI']._serialized_start=375
  _globals['_ROBOTARMAI']._serialized_end=503
# @@protoc_insertion_point(module_scope)
