# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_arm_pb2 as robot__arm__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_arm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotArmAIStub:
    """AI 서버(EdgeXpert, 서버) ↔ 노트북(클라이언트).
    노트북이 명령(+음성/이미지/탐지/상태)을 보내면 AI가 의도분류·계획(DSL)을 돌려준다.
    모델은 서버 시작 시 1회 로드(warm) → 요청마다 추론만.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Plan = channel.unary_unary(
                '/robotarm.RobotArmAI/Plan',
                request_serializer=robot__arm__pb2.PlanRequest.SerializeToString,
                response_deserializer=robot__arm__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/robotarm.RobotArmAI/Health',
                request_serializer=robot__arm__pb2.HealthRequest.SerializeToString,
                response_deserializer=robot__arm__pb2.HealthResponse.FromString,
                _registered_method=True)


class RobotArmAIServicer:
    """AI 서버(EdgeXpert, 서버) ↔ 노트북(클라이언트).
    노트북이 명령(+음성/이미지/탐지/상태)을 보내면 AI가 의도분류·계획(DSL)을 돌려준다.
    모델은 서버 시작 시 1회 로드(warm) → 요청마다 추론만.
    """

    def Plan(self, request, context):
        """명령/질문 → 의도+답변/DSL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotArmAIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Plan': grpc.unary_unary_rpc_method_handler(
                    servicer.Plan,
                    request_deserializer=robot__arm__pb2.PlanRequest.FromString,
                    response_serializer=robot__arm__pb2.PlanResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=robot__arm__pb2.HealthRequest.FromString,
                    response_serializer=robot__arm__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotarm.RobotArmAI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotarm.RobotArmAI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotArmAI:
    """AI 서버(EdgeXpert, 서버) ↔ 노트북(클라이언트).
    노트북이 명령(+음성/이미지/탐지/상태)을 보내면 AI가 의도분류·계획(DSL)을 돌려준다.
    모델은 서버 시작 시 1회 로드(warm) → 요청마다 추론만.
    """

    @staticmethod
    def Plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotarm.RobotArmAI/Plan',
            robot__arm__pb2.PlanRequest.SerializeToString,
            robot__arm__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotarm.RobotArmAI/Health',
            robot__arm__pb2.HealthRequest.SerializeToString,
            robot__arm__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
